name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./Coursework.sln || true

      - name: Build
        run: dotnet build ./Coursework.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Coursework.sln --configuration Release --no-build







 


